# Generated by Django 6.0.4 on 2026-09-05 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0066_alter_scheduledtask_task_type'),
        ('monitoring', '0012_monitorcheck'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=False, help_text='Off by default. While off, the public URL returns 404.')),
                ('token', models.CharField(db_index=True, help_text='Random component of the public URL. Rotating it breaks every existing link immediately.', max_length=64, unique=True)),
                ('title', models.CharField(blank=True, help_text='Heading on the page. Defaults to "Service status".', max_length=120)),
                ('intro', models.TextField(blank=True, help_text='Optional paragraph under the heading. Plain text.')),
                ('show_uptime', models.BooleanField(default=True, help_text='Show 30 / 90 / 365-day uptime percentages per service.')),
                ('show_response_time', models.BooleanField(default=False, help_text='Show the last response time. Off by default — it invites questions that a status page cannot answer.')),
                ('refresh_seconds', models.PositiveIntegerField(default=120, help_text='How often the page reloads itself. Minimum 30.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_pages_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, help_text='Leave empty for a page not tied to one client.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_pages', to='core.organization')),
            ],
            options={
                'db_table': 'statuspage_pages',
                'ordering': ['organization__name', 'title'],
            },
        ),
        migrations.CreateModel(
            name='StatusPageService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='What the public sees. Never the monitor name or its URL.', max_length=120)),
                ('description', models.CharField(blank=True, help_text='Optional one-liner, e.g. "Webmail and calendar".', max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True, help_text='Hide without deleting — keeps the history if you re-show it.')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_page_entries', to='monitoring.websitemonitor')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='statuspage.statuspage')),
            ],
            options={
                'db_table': 'statuspage_services',
                'ordering': ['sort_order', 'display_name'],
                'unique_together': {('page', 'monitor')},
            },
        ),
    ]
