# Generated by Django 6.0.4 on 2026-09-05 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuspage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField(blank=True, help_text='What is happening and what the client should expect. Plain text — this is read by people outside the business.')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_cancelled', models.BooleanField(default=False, help_text='Called off. Stays on the page as cancelled rather than vanishing, so anyone who read the original notice can see it is no longer happening.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_windows_created', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_windows', to='statuspage.statuspage')),
                ('services', models.ManyToManyField(blank=True, help_text='Leave empty if the work affects everything on the page.', related_name='maintenance_windows', to='statuspage.statuspageservice')),
            ],
            options={
                'db_table': 'statuspage_maintenance_windows',
                'ordering': ['-starts_at'],
            },
        ),
    ]
