# Generated by Django 6.0.4 on 2026-09-05 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0062_ticket_is_status_page'),
        ('statuspage', '0002_maintenancewindow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusPageIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='What the public sees. Not the ticket subject.', max_length=200)),
                ('started_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Set when the incident is over. Until then it reads as ongoing.', null=True)),
                ('root_cause', models.TextField(blank=True, help_text='Optional, published once known. Plain text.')),
                ('is_published', models.BooleanField(default=True, help_text='Unpublish to pull it from the page without deleting the record and its updates.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_page_incidents_created', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='statuspage.statuspage')),
                ('services', models.ManyToManyField(blank=True, help_text='Leave empty if the incident affected everything on the page.', related_name='incidents', to='statuspage.statuspageservice')),
                ('ticket', models.ForeignKey(blank=True, help_text='Optional. Links the published incident back to the work.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_page_incidents', to='psa.ticket')),
            ],
            options={
                'db_table': 'statuspage_incidents',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('investigating', 'Investigating'), ('identified', 'Identified'), ('monitoring', 'Monitoring'), ('resolved', 'Resolved')], default='investigating', max_length=20)),
                ('body', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_updates_posted', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='statuspage.statuspageincident')),
            ],
            options={
                'db_table': 'statuspage_incident_updates',
                'ordering': ['posted_at'],
            },
        ),
    ]
