# Generated by Django 6.0.4 on 2026-09-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuspage', '0003_statuspageincident_incidentupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuspage',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public — anyone with the link'), ('portal', 'Portal — signed-in client users only')], default='public', help_text='Public pages are read by anyone holding the link. Portal pages are read only by signed-in users of the client they belong to, and their link does not work anonymously.', max_length=10),
        ),
        migrations.AlterField(
            model_name='statuspage',
            name='is_enabled',
            field=models.BooleanField(default=False, help_text='Off by default. While off, the URL returns 404.'),
        ),
    ]
