# Generated by Django 6.0.4 on 2026-09-03 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_add_psa_ticket_and_alerts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerWallboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=False, help_text='Off by default. While off, the public URL returns 404.')),
                ('token', models.CharField(db_index=True, help_text='Random component of the public URL. Rotating it breaks every existing link immediately.', max_length=64, unique=True)),
                ('title', models.CharField(blank=True, help_text='Heading on the board. Defaults to "Schedule".', max_length=120)),
                ('days_ahead', models.PositiveSmallIntegerField(default=1, help_text='How many days to show, starting today. 1 = today only.')),
                ('refresh_seconds', models.PositiveIntegerField(default=60, help_text='How often the board reloads itself. Minimum 15.')),
                ('show_client_names', models.BooleanField(default=True, help_text='Show which client each job is for. Turn off if the screen is visible to visitors.')),
                ('show_technician_names', models.BooleanField(default=True)),
                ('show_ticket_numbers', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduler_wallboards_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scheduling_wallboards',
            },
        ),
    ]
