# Generated by Django 6.0.4 on 2026-09-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_schedulerwallboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='alert_before_unit',
            field=models.CharField(choices=[('hours', 'hours'), ('days', 'days')], default='hours', help_text='How the lead time was entered. Display only — `alert_before_hours` is what alerting uses.', max_length=10),
        ),
    ]
