# Generated by Django 6.0.1 on 2026-01-14 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_snyk_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SnykScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.CharField(help_text='Unique scan identifier', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, help_text='Scan duration in seconds', null=True)),
                ('total_vulnerabilities', models.IntegerField(default=0)),
                ('critical_count', models.IntegerField(default=0)),
                ('high_count', models.IntegerField(default=0)),
                ('medium_count', models.IntegerField(default=0)),
                ('low_count', models.IntegerField(default=0)),
                ('scan_output', models.TextField(blank=True, help_text='Full Snyk scan output')),
                ('error_message', models.TextField(blank=True, help_text='Error message if scan failed')),
                ('severity_threshold', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='high', max_length=20)),
                ('project_path', models.CharField(default='/home/administrator', max_length=500)),
                ('vulnerabilities', models.JSONField(blank=True, default=dict, help_text='Detailed vulnerability information')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snyk_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'snyk_scans',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['-started_at'], name='snyk_scans_started_0a5284_idx'), models.Index(fields=['status'], name='snyk_scans_status_3ec6a4_idx'), models.Index(fields=['critical_count', 'high_count'], name='snyk_scans_critica_ed64b6_idx')],
            },
        ),
    ]
