# Generated by Django 6.0.1 on 2026-01-29 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_whitelabeling_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='sms_account_sid',
            field=models.CharField(blank=True, help_text='SMS provider account SID/API key', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='sms_auth_token',
            field=models.CharField(blank=True, help_text='SMS provider auth token (encrypted)', max_length=500),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='sms_enabled',
            field=models.BooleanField(default=False, help_text='Enable SMS functionality'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='sms_from_number',
            field=models.CharField(blank=True, help_text='From phone number (E.164 format, e.g., +15551234567)', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='sms_provider',
            field=models.CharField(choices=[('twilio', 'Twilio'), ('plivo', 'Plivo'), ('sinch', 'Sinch'), ('vonage', 'Vonage/Nexmo'), ('aws_sns', 'AWS SNS'), ('telnyx', 'Telnyx')], default='twilio', help_text='SMS provider for sending navigation links and notifications', max_length=20),
        ),
        migrations.AlterField(
            model_name='firewalllog',
            name='block_reason',
            field=models.CharField(choices=[('country_blocklist', 'Country in blocklist'), ('country_not_in_allowlist', 'Country not in allowlist'), ('geoip_lookup_failed', 'GeoIP lookup failed'), ('ip_blocklist', 'IP in blocklist'), ('ip_not_in_allowlist', 'IP not in allowlist')], max_length=50),
        ),
        migrations.AlterField(
            model_name='relation',
            name='relation_type',
            field=models.CharField(choices=[('applies_to', 'Applies To'), ('contains', 'Contains'), ('credentials', 'Credentials'), ('depends_on', 'Depends On'), ('documented_by', 'Documented By'), ('related_to', 'Related To'), ('responsible_for', 'Responsible For'), ('used_by', 'Used By')], default='related_to', max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='last_status',
            field=models.CharField(choices=[('failed', 'Failed'), ('pending', 'Pending'), ('running', 'Running'), ('success', 'Success')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='task_type',
            field=models.CharField(choices=[('cleanup_stuck_scans', 'Cleanup Stuck Security Scans'), ('domain_expiry_check', 'Domain Expiry Check'), ('equipment_catalog_update', 'Equipment Catalog Update'), ('password_breach_scan', 'Password Breach Scanning'), ('psa_sync', 'PSA Synchronization'), ('rmm_sync', 'RMM Synchronization'), ('ssl_expiry_check', 'SSL Certificate Expiry Check'), ('update_check', 'System Update Check'), ('website_monitoring', 'Website Monitoring Checks')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='snykscan',
            name='severity_threshold',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('low', 'Low'), ('medium', 'Medium')], default='high', max_length=20),
        ),
        migrations.AlterField(
            model_name='snykscan',
            name='status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('completed', 'Completed'), ('failed', 'Failed'), ('pending', 'Pending'), ('running', 'Running'), ('timeout', 'Timed Out')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='snyk_scan_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('hourly', 'Every Hour'), ('manual', 'Manual Only'), ('weekly', 'Weekly')], default='daily', help_text='How often to run automatic scans', max_length=20),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='snyk_severity_threshold',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('low', 'Low'), ('medium', 'Medium')], default='high', help_text='Minimum severity level to report', max_length=20),
        ),
    ]
