# Generated by Django 6.0.1 on 2026-01-30 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_sms_provider_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='securenote',
            name='access_token',
            field=models.CharField(blank=True, help_text='Unique token for link-only access', max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='securenote',
            name='label',
            field=models.CharField(blank=True, help_text='Optional label for tracking/organizing secret links', max_length=255),
        ),
        migrations.AddField(
            model_name='securenote',
            name='link_only',
            field=models.BooleanField(default=False, help_text='Link-only mode: no recipients, share via URL'),
        ),
    ]
