# Generated by Django 6.0.1 on 2026-01-31 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_securenote_max_views_securenoteaccesslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='stay_on_page_after_org_switch',
            field=models.BooleanField(default=True, help_text='Stay on current page when switching organizations instead of redirecting to dashboard'),
        ),
    ]
