# Generated by Django 6.0.1 on 2026-02-08 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_add_global_locations_map_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='locations_map_enabled',
            field=models.BooleanField(default=True, help_text='Enable location maps and geocoding features'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='secure_notes_enabled',
            field=models.BooleanField(default=True, help_text='Enable secure ephemeral notes feature'),
        ),
    ]
