# Generated by Django 6.0.1 on 2026-02-12 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_update_organization_type_to_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='webhooks_enabled',
            field=models.BooleanField(default=True, help_text='Enable Webhooks for event notifications'),
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for this webhook', max_length=255)),
                ('url', models.URLField(help_text='URL to send webhook POST requests to', max_length=500)),
                ('events', models.JSONField(default=list, help_text='List of event types to trigger this webhook')),
                ('secret', models.CharField(blank=True, help_text='Secret key for signing webhook payloads (optional)', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this webhook')),
                ('custom_headers', models.JSONField(blank=True, default=dict, help_text='Custom HTTP headers to include in requests (e.g., Authorization)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_webhooks', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Organization this webhook belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='core.organization')),
            ],
            options={
                'db_table': 'webhooks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('payload', models.JSONField(help_text='The JSON payload sent to the webhook')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Request duration in milliseconds', null=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='core.webhook')),
            ],
            options={
                'verbose_name_plural': 'Webhook deliveries',
                'db_table': 'webhook_deliveries',
                'ordering': ['-delivered_at'],
            },
        ),
        migrations.AddIndex(
            model_name='webhook',
            index=models.Index(fields=['organization', 'is_active'], name='webhooks_organiz_211990_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['webhook', '-delivered_at'], name='webhook_del_webhook_d0d563_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['status'], name='webhook_del_status_269a2c_idx'),
        ),
    ]
