# Generated by Django 6.0.4 on 2026-09-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_betatesterrequest_source_install'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='geoip_map_background_image',
            field=models.ImageField(blank=True, help_text="Backdrop image used when the mode is 'image'.", null=True, upload_to='branding/geoip/'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='geoip_map_background_mode',
            field=models.CharField(choices=[('pattern', 'Colour pattern'), ('random', 'Random (a different pattern each visit)'), ('image', 'Uploaded image')], default='pattern', help_text='Backdrop behind the GeoIP world map.', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='geoip_map_background_pattern',
            field=models.CharField(choices=[('slate', 'Slate'), ('ocean', 'Ocean'), ('midnight', 'Midnight'), ('terrain', 'Terrain'), ('sunset', 'Sunset'), ('mono', 'Mono')], default='slate', help_text="Which colour pattern to use when the mode is 'pattern'.", max_length=40),
        ),
    ]
