# Generated by Django 6.0.4 on 2026-09-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_geoip_map_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='background_color',
            field=models.CharField(blank=True, default='#1a1a2e', help_text='Hex colour used when the colour style is solid.', max_length=7),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='background_color_style',
            field=models.CharField(choices=[('solid', 'Solid colour'), ('preset', 'Preset pattern')], default='solid', help_text="Solid colour or preset pattern, when the policy is 'colour'.", max_length=20),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='background_image',
            field=models.ImageField(blank=True, help_text="Background image used when the policy is 'static image'.", null=True, upload_to='branding/backgrounds/'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='background_policy',
            field=models.CharField(choices=[('user', 'User controlled — each person picks their own'), ('image', 'Static image — one uploaded image for everyone'), ('color', 'Colour or pattern — one look for everyone'), ('random', 'Random images — a different image each page load')], default='user', help_text="Who decides the app background. Anything other than 'user controlled' overrides every user's own setting.", max_length=20),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='background_preset',
            field=models.CharField(blank=True, choices=[('abstract-1', 'Purple Gradient'), ('abstract-2', 'Blue Gradient'), ('abstract-3', 'Orange Coral'), ('abstract-4', 'Teal Wave'), ('abstract-5', 'Pink Nebula'), ('abstract-6', 'Cyan Fluid'), ('abstract-7', 'Red Geometric'), ('abstract-8', 'Blue Teal'), ('abstract-9', 'Yellow Gold'), ('abstract-10', 'Indigo Dark'), ('abstract-11', 'Magenta Flow'), ('abstract-12', 'Navy Space')], default='abstract-1', help_text='Which preset pattern to use when the colour style is preset.', max_length=40),
        ),
    ]
