# Generated by Django 6.0.4 on 2026-09-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_alter_scheduledtask_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtask',
            name='task_type',
            field=models.CharField(choices=[('asset_age_check', 'Asset Age Warning Check'), ('cleanup_stuck_scans', 'Cleanup Stuck Security Scans'), ('domain_expiry_check', 'Domain Expiry Check'), ('equipment_catalog_update', 'Equipment Catalog Update'), ('firmware_check', 'Firmware Update Check'), ('password_breach_scan', 'Password Breach Scanning'), ('python_dep_scan', 'Python Dependency Vulnerability Scan'), ('system_warnings_digest', 'System Warnings Digest Email'), ('vault_password_expiry', 'Vault Password Expiry Notifications'), ('prune_monitor_checks', 'Prune Website Check History'), ('network_config_backup', 'Network Device Config Backup'), ('psa_sync', 'PSA Synchronization'), ('accounting_sync', 'Accounting Sync (QuickBooks Online / Xero)'), ('rmm_sync', 'RMM Synchronization'), ('scheduling_alerts', 'Scheduled Task Alerts'), ('security_scan', 'Automated Security Scan'), ('ssl_expiry_check', 'SSL Certificate Expiry Check'), ('update_check', 'System Update Check'), ('warranty_check', 'Warranty Expiry Check'), ('website_monitoring', 'Website Monitoring Checks')], max_length=50, unique=True),
        ),
    ]
