# Generated by Django 6.0.4 on 2026-09-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_alter_scheduledtask_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='background_color_style',
            field=models.CharField(choices=[('solid', 'Solid colour'), ('preset', 'Preset pattern')], default='preset', help_text="Solid colour or preset pattern, when the policy is 'colour'.", max_length=20),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='background_policy',
            field=models.CharField(choices=[('user', 'User controlled — each person picks their own'), ('image', 'Static image — one uploaded image for everyone'), ('color', 'Colour or pattern — one look for everyone'), ('random', 'Random images — a different image each page load')], default='color', help_text="Who decides the app background. Anything other than 'user controlled' overrides every user's own setting.", max_length=20),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='background_preset',
            field=models.CharField(blank=True, choices=[('abstract-1', 'Purple Gradient'), ('abstract-2', 'Blue Gradient'), ('abstract-3', 'Orange Coral'), ('abstract-4', 'Teal Wave'), ('abstract-5', 'Pink Nebula'), ('abstract-6', 'Cyan Fluid'), ('abstract-7', 'Red Geometric'), ('abstract-8', 'Blue Teal'), ('abstract-9', 'Yellow Gold'), ('abstract-10', 'Indigo Dark'), ('abstract-11', 'Magenta Flow'), ('abstract-12', 'Navy Space')], default='abstract-12', help_text='Which preset pattern to use when the colour style is preset.', max_length=40),
        ),
    ]
