# Generated by Django 6.0.4 on 2026-09-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_alter_systemsetting_background_color_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='background_policy',
            field=models.CharField(choices=[('user', 'User controlled — each person picks their own'), ('image', 'Static image — one uploaded image for everyone'), ('color', 'Colour or pattern — one look for everyone'), ('random', 'Random images — a different image each page load')], default='user', help_text="Who decides the app background. Anything other than 'user controlled' overrides every user's own setting.", max_length=20),
        ),
    ]
