# Generated by Django 6.0.4 on 2026-09-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_alter_systemsetting_background_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtask',
            name='last_run_at',
            field=models.DateTimeField(blank=True, help_text='When the last run started', null=True),
        ),
    ]
