# Generated by Django 6.0.4 on 2026-09-05 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0025_remediationsuggestion'),
        ('core', '0066_alter_scheduledtask_task_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(help_text='The configuration text as captured.')),
                ('content_hash', models.CharField(db_index=True, help_text='SHA-256 of the body. Used to detect an unchanged config.', max_length=64)),
                ('captured_at', models.DateTimeField(db_index=True)),
                ('last_seen_at', models.DateTimeField(help_text='Most recent capture that produced this exact config. A device left alone moves this rather than writing a copy.')),
                ('source', models.CharField(choices=[('manual', 'Pasted or uploaded by hand'), ('ssh', 'Collected over SSH'), ('scp', 'Collected over SCP'), ('api', 'Collected from a vendor API'), ('import', 'Imported from another system')], default='manual', max_length=20)),
                ('firmware_version', models.CharField(blank=True, help_text='Running firmware at capture time, when the device reports it.', max_length=120)),
                ('is_approved', models.BooleanField(default=False, help_text='Marks this as the known-good configuration to compare against.')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_backups', to='assets.asset')),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_backups_captured', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_backups', to='core.organization')),
            ],
            options={
                'db_table': 'netconfig_backups',
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['asset', '-captured_at'], name='netcfg_asset_time_idx')],
            },
        ),
    ]
