# Generated by Django 6.0.4 on 2026-09-05 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0025_remediationsuggestion'),
        ('core', '0067_alter_scheduledtask_task_type'),
        ('netconfig', '0001_initial'),
        ('vault', '0014_webextensionauthtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=True, help_text='Uncheck to skip this device on scheduled runs.')),
                ('host', models.CharField(help_text="Hostname or IP to connect to. Falls back to nothing — the asset's own IP is not assumed, because the management address is often not the one on the asset record.", max_length=255)),
                ('port', models.PositiveIntegerField(default=22)),
                ('username', models.CharField(max_length=150)),
                ('adapter', models.CharField(default='generic', help_text='Platform. Decides which command prints the running config.', max_length=40)),
                ('config_command', models.CharField(blank=True, help_text='Overrides the adapter default. For an appliance nobody wrote an adapter for.', max_length=255)),
                ('version_command', models.CharField(blank=True, max_length=255)),
                ('cadence_hours', models.PositiveIntegerField(default=24, help_text='Minimum hours between scheduled collections. Default daily.')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_backup_target', to='assets.asset')),
                ('credential', models.ForeignKey(blank=True, help_text='Vault entry holding the password. Deleting it disables collection rather than silently falling back to anything.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_backup_targets', to='vault.password')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_backup_targets', to='core.organization')),
            ],
            options={
                'db_table': 'netconfig_targets',
                'ordering': ['asset__name'],
            },
        ),
    ]
