# Generated by Django 6.0.4 on 2026-09-05 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netconfig', '0002_backuptarget'),
        ('psa', '0062_ticket_is_status_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='configbackup',
            name='change_request',
            field=models.ForeignKey(blank=True, help_text='The approved change this snapshot fell inside, when it did.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_backups', to='psa.changerequest'),
        ),
        migrations.AddField(
            model_name='configbackup',
            name='drift_state',
            field=models.CharField(blank=True, choices=[('', 'Not classified'), ('baseline', 'Matches the approved baseline'), ('expected', 'Changed inside an approved change window'), ('unauthorized', 'Changed outside any approved change window'), ('no_baseline', 'No approved baseline to compare against')], default='', help_text='How this snapshot compared to the approved baseline when it was taken.', max_length=20),
        ),
    ]
