# Generated by Django 6.0.4 on 2026-09-06 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0026_asset_vendor_end_of_life_asset_vendor_end_of_support'),
        ('core', '0069_alter_systemsetting_background_policy'),
        ('locations', '0008_add_wan_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkDiscoveryImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('device_count', models.PositiveIntegerField(default=0)),
                ('imported_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('is_dry_run', models.BooleanField(default=False, help_text='A preview: results were parsed and matched but nothing was written to the asset register.')),
                ('raw_payload', models.JSONField(blank=True, default=dict, help_text='Summarised submission. Not the full device list — that is in the result rows.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_discovery_imports', to='locations.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_discovery_imports', to='core.organization')),
                ('uploaded_by_user', models.ForeignKey(blank=True, help_text='Whoever generated the token. The upload itself is unauthenticated, so this is attribution, not identity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_discovery_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'network_discovery_imports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NetworkDiscoveryAssetResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=32)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('vendor', models.CharField(blank=True, max_length=255)),
                ('device_type', models.CharField(blank=True, max_length=60)),
                ('discovery_method', models.CharField(blank=True, max_length=60)),
                ('status', models.CharField(choices=[('created', 'Created a new asset'), ('updated', 'Updated an existing asset'), ('matched', 'Matched an existing asset; nothing to change'), ('skipped', 'Skipped'), ('error', 'Error'), ('preview', 'Preview only — nothing written')], max_length=20)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_discovery_results', to='assets.asset')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_discovery_results', to='locations.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_discovery_results', to='core.organization')),
                ('discovery_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='network_discovery.networkdiscoveryimport')),
            ],
            options={
                'db_table': 'network_discovery_asset_results',
                'ordering': ['ip_address', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NetworkDiscoveryToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(db_index=True, help_text='SHA-256 of the token. The plaintext is never stored.', max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, help_text='First successful use.', null=True)),
                ('max_uses', models.PositiveIntegerField(default=1, help_text='Single-use by default. A sweep that has to be re-run gets a new token rather than a reusable one.')),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('source_ip_last_used', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent_last_used', models.CharField(blank=True, max_length=255)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_discovery_tokens_created', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_discovery_tokens', to='locations.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_discovery_tokens', to='core.organization')),
            ],
            options={
                'db_table': 'network_discovery_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='networkdiscoveryimport',
            name='token',
            field=models.ForeignKey(blank=True, help_text='The token used. SET_NULL so an import survives a token purge.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports', to='network_discovery.networkdiscoverytoken'),
        ),
        migrations.AddIndex(
            model_name='networkdiscoverytoken',
            index=models.Index(fields=['organization', 'location', '-created_at'], name='nd_token_org_loc_idx'),
        ),
    ]
