# Generated by Django 6.0.4 on 2026-09-06 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0026_asset_vendor_end_of_life_asset_vendor_end_of_support'),
        ('core', '0069_alter_systemsetting_background_policy'),
        ('locations', '0008_add_wan_model'),
        ('network_discovery', '0001_initial'),
        ('vault', '0014_webextensionauthtoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoverySite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='What this collector is, e.g. "HQ closet Raspberry Pi".', max_length=120)),
                ('key_hash', models.CharField(db_index=True, help_text='SHA-256 of the collector key. The plaintext is never stored.', max_length=64, unique=True)),
                ('key_rotated_at', models.DateTimeField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=True, help_text='Disable to stop a collector without deleting its history.')),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('subnets', models.JSONField(blank=True, default=list, help_text='CIDR ranges to sweep. Empty means "work it out locally", the same behaviour as the Phase 32 script.')),
                ('scan_interval_minutes', models.PositiveIntegerField(default=1440, help_text='How often the collector should scan. Daily by default; an hourly sweep of a large site is mostly noise.')),
                ('snmp_enabled', models.BooleanField(default=False, help_text='Read SNMP for neighbour and port data. Community strings live in the vault, never here.')),
                ('classify_enabled', models.BooleanField(default=False, help_text='Probe a handful of well-known ports to guess device types.')),
                ('last_seen_at', models.DateTimeField(blank=True, help_text='Last time the collector asked for its configuration.', null=True)),
                ('last_scan_at', models.DateTimeField(blank=True, null=True)),
                ('last_source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('collector_version', models.CharField(blank=True, max_length=40)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovery_sites_created', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovery_sites', to='locations.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovery_sites', to='core.organization')),
                ('snmp_credential', models.ForeignKey(blank=True, help_text='Vault entry holding the SNMP community or v3 credentials.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovery_sites', to='vault.password')),
            ],
            options={
                'db_table': 'network_discovery_sites',
                'ordering': ['organization__name', 'name'],
                'unique_together': {('organization', 'location', 'name')},
            },
        ),
        migrations.CreateModel(
            name='NetworkLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_port', models.CharField(blank=True, max_length=120)),
                ('remote_name', models.CharField(blank=True, max_length=255)),
                ('remote_port', models.CharField(blank=True, max_length=120)),
                ('remote_mac', models.CharField(blank=True, max_length=32)),
                ('remote_description', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('lldp', 'LLDP'), ('cdp', 'CDP'), ('manual', 'Entered by hand')], default='lldp', max_length=10)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(db_index=True)),
                ('local_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_links_local', to='assets.asset')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_links', to='locations.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_links', to='core.organization')),
                ('remote_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_links_remote', to='assets.asset')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='network_discovery.discoverysite')),
            ],
            options={
                'db_table': 'network_discovery_links',
                'ordering': ['local_asset__name', 'local_port'],
                'indexes': [models.Index(fields=['organization', 'location', '-last_seen_at'], name='nd_link_org_loc_idx')],
                'unique_together': {('local_asset', 'local_port', 'remote_name', 'remote_port')},
            },
        ),
        migrations.CreateModel(
            name='SwitchPortEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_name', models.CharField(max_length=120)),
                ('vlan_id', models.PositiveIntegerField(blank=True, null=True)),
                ('mac_address', models.CharField(db_index=True, max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(db_index=True)),
                ('device_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='switch_port_entries', to='assets.asset')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='switch_ports', to='locations.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='switch_ports', to='core.organization')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='switch_ports', to='network_discovery.discoverysite')),
                ('switch_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='switch_ports', to='assets.asset')),
            ],
            options={
                'db_table': 'network_discovery_switch_ports',
                'ordering': ['switch_asset__name', 'port_name', 'mac_address'],
                'indexes': [models.Index(fields=['organization', 'mac_address'], name='nd_port_org_mac_idx')],
                'unique_together': {('switch_asset', 'port_name', 'vlan_id', 'mac_address')},
            },
        ),
    ]
