# Generated by Django 6.0.4 on 2026-09-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_discovery', '0002_discoverysite_networklink_switchportentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoverysite',
            name='scan_requested_at',
            field=models.DateTimeField(blank=True, help_text='Set by an operator asking for a scan. Cleared when the collector next fetches its configuration.', null=True),
        ),
    ]
