# Generated by Django 6.0.4 on 2026-07-26 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0027_warrantyconnection'),
        ('psa', '0056_ticketcomment_voice_meta_tickettimeentry_end_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailingestionconfig',
            name='graph_mailbox',
            field=models.CharField(blank=True, help_text='Shared mailbox / user UPN to poll via Graph, e.g. support@contoso.com', max_length=320),
        ),
        migrations.AddField(
            model_name='emailingestionconfig',
            name='m365_connection',
            field=models.ForeignKey(blank=True, help_text='M365 tenant connection whose app registration is used for mailbox access (needs the Mail.Read application permission).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_ingestion_configs', to='integrations.m365connection'),
        ),
        migrations.AddField(
            model_name='emailingestionconfig',
            name='source',
            field=models.CharField(choices=[('imap', 'IMAP'), ('graph', 'Microsoft 365 (Graph API)')], default='imap', max_length=10),
        ),
        migrations.AlterField(
            model_name='emailingestionconfig',
            name='imap_host',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='emailingestionconfig',
            name='username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
