# Generated by Django 6.0.4 on 2026-07-26 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_betatesterrequest_source_install'),
        ('psa', '0057_emailingestionconfig_graph_mailbox_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailingestionconfig',
            name='graph_send_last_error',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='emailingestionconfig',
            name='graph_send_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailingestionconfig',
            name='outbound_method',
            field=models.CharField(choices=[('smtp', 'SMTP (existing)'), ('graph', 'Microsoft Graph')], default='smtp', help_text='How staff replies are sent. Graph requires an M365 connection + mailbox.', max_length=10),
        ),
        migrations.AddField(
            model_name='emailingestionconfig',
            name='smtp_fallback_enabled',
            field=models.BooleanField(default=False, help_text='If Graph is known-unavailable before sending, fall back to SMTP.'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='graph_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='transport',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.CreateModel(
            name='EmailOutboundJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport', models.CharField(default='graph', max_length=10)),
                ('operation', models.CharField(choices=[('send', 'sendMail'), ('reply', 'reply'), ('reply_all', 'replyAll')], default='send', max_length=12)),
                ('mailbox', models.CharField(max_length=320)),
                ('graph_message_id', models.CharField(blank=True, max_length=255)),
                ('to_recipients', models.JSONField(blank=True, default=list)),
                ('cc_recipients', models.JSONField(blank=True, default=list)),
                ('bcc_recipients', models.JSONField(blank=True, default=list)),
                ('reply_to', models.JSONField(blank=True, default=list)),
                ('subject', models.CharField(blank=True, max_length=998)),
                ('body_html', models.TextField(blank=True)),
                ('body_text', models.TextField(blank=True)),
                ('save_to_sent_items', models.BooleanField(default=True)),
                ('attachment_ids', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent (accepted)'), ('failed', 'Failed'), ('uncertain', 'Uncertain — needs review')], db_index=True, default='queued', max_length=12)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=5)),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('ms_request_id', models.CharField(blank=True, max_length=200)),
                ('last_error', models.TextField(blank=True)),
                ('error_category', models.CharField(blank=True, max_length=20)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_jobs', to='psa.emailingestionconfig')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('email_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_job', to='psa.emailmessage')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_outbound_jobs', to='core.organization')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_outbound_jobs', to='psa.ticket')),
            ],
            options={
                'db_table': 'psa_email_outbound_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='psa_email_o_status_58e625_idx'), models.Index(fields=['organization', 'status'], name='psa_email_o_organiz_d43329_idx')],
            },
        ),
    ]
