# Generated by Django 6.0.4 on 2026-09-03 20:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0058_emailingestionconfig_graph_send_last_error_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='accounting_external_id',
            field=models.CharField(blank=True, db_index=True, help_text='Payment ID in the external accounting system.', max_length=120),
        ),
        migrations.AddField(
            model_name='payment',
            name='accounting_provider',
            field=models.CharField(blank=True, help_text='quickbooks_online | xero | etc. Blank for manual entries.', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('accounting_external_id__gt', '')), fields=('accounting_provider', 'accounting_external_id'), name='uniq_payment_per_provider_txn'),
        ),
    ]
