# Generated by Django 6.0.4 on 2026-09-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0059_payment_accounting_external_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='provider_synced_at',
            field=models.DateTimeField(blank=True, help_text='When the provider copy of this invoice was last read back.', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='provider_total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Invoice total as the accounting provider currently reports it. Differs from `total` when the invoice was edited provider-side.', max_digits=12, null=True),
        ),
    ]
