# Generated by Django 6.0.4 on 2026-09-03 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_alter_scheduledtask_task_type'),
        ('inventory', '0003_tool'),
        ('psa', '0060_invoice_provider_synced_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketKitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('tool', 'Tool'), ('inventory', 'Inventory item'), ('other', 'Other / not stocked')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('packed', models.BooleanField(default=False)),
                ('packed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_kit_items', to='inventory.inventoryitem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psa_ticket_kit_items', to='core.organization')),
                ('packed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psa_kit_items_packed', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kit_items', to='psa.ticket')),
                ('tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_kit_items', to='inventory.tool')),
            ],
            options={
                'db_table': 'psa_ticket_kit_items',
                'ordering': ['sort_order', 'kind', 'pk'],
                'indexes': [models.Index(fields=['ticket', 'kind'], name='psa_ticket__ticket__70e3f3_idx'), models.Index(fields=['organization', 'packed'], name='psa_ticket__organiz_4f9a8a_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('tool__isnull', False)), fields=('ticket', 'tool'), name='uniq_kit_tool_per_ticket'), models.UniqueConstraint(condition=models.Q(('inventory_item__isnull', False)), fields=('ticket', 'inventory_item'), name='uniq_kit_item_per_ticket')],
            },
        ),
    ]
