# Generated by Django 6.0.4 on 2026-09-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0061_ticketkititem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_status_page',
            field=models.BooleanField(db_index=True, default=False, help_text='Flag this ticket as a publishable incident. Publishing it is a separate, deliberate step on a status page.'),
        ),
    ]
