# Generated by Django 6.0.4 on 2026-09-05 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_alter_scheduledtask_task_type'),
        ('psa', '0062_ticket_is_status_page'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Retire a template without deleting it — projects built from it keep their tasks either way.')),
                ('default_is_billable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_templates_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='The MSP that owns this template.', on_delete=django.db.models.deletion.CASCADE, related_name='project_templates', to='core.organization')),
            ],
            options={
                'db_table': 'psa_project_templates',
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProjectTemplateTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('is_milestone', models.BooleanField(default=False)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('due_offset_days', models.IntegerField(blank=True, help_text='Days from the project start. 0 is the start date itself; leave empty for a task with no date.', null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='psa.projecttemplatetask')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_tasks', to='psa.projecttemplate')),
            ],
            options={
                'db_table': 'psa_project_template_tasks',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
