# Generated by Django 6.0.4 on 2026-09-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0063_projecttemplate_projecttemplatetask'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='budget_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Money this project is allowed to consume. Leave empty for no monetary budget.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='budget_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hours this project is allowed to consume. Leave empty for no hours budget.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='budget_warn_at_percent',
            field=models.PositiveIntegerField(default=80, help_text='Percentage of budget at which the project reads as at risk.'),
        ),
    ]
