# Generated by Django 6.0.4 on 2026-09-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0064_project_budget_amount_project_budget_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='depends_on',
            field=models.ManyToManyField(blank=True, help_text='Tasks that must finish before this one can start.', related_name='dependents', to='psa.projecttask'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='start_date',
            field=models.DateField(blank=True, help_text='When the work is planned to begin. A task with only a due date is drawn as a single-day marker.', null=True),
        ),
    ]
