# Generated by Django 6.0.4 on 2026-09-06 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0065_projecttask_depends_on_projecttask_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='project',
            field=models.ForeignKey(blank=True, help_text='The project this invoice was generated from, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='psa.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='billing_type',
            field=models.CharField(choices=[('time_materials', 'Time and materials — bill logged hours'), ('fixed_fee', 'Fixed fee — one agreed amount'), ('milestone', 'Milestone — bill each milestone as it lands')], default='time_materials', help_text='What an invoice generated from this project contains.', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='fixed_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The agreed amount, when the billing type is fixed fee.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='billed_on_invoice',
            field=models.ForeignKey(blank=True, help_text='The invoice this milestone was billed on, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billed_milestones', to='psa.invoice'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='billing_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='What this milestone bills for, on a milestone-billed project. Ignored elsewhere.', max_digits=12, null=True),
        ),
    ]
