# Generated by Django 6.0.4 on 2026-09-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0066_invoice_project_project_billing_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sla_paused_at',
            field=models.DateTimeField(blank=True, help_text='When the current SLA pause began. Null when running.', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_paused_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Total minutes this ticket has spent in a paused status.'),
        ),
    ]
