# Generated by Django 6.0.4 on 2026-09-16 01:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_alter_systemsetting_background_policy'),
        ('integrations', '0030_alter_accountingauditlog_action'),
        ('psa', '0067_sla_pause_accounting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='billing_period_start',
            field=models.DateField(blank=True, db_index=True, help_text='Start of the billing period this invoice covers, when it was generated from a contract.', null=True),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('billing_period_start__isnull', False), ('is_credit_memo', False)), fields=('source_contract', 'billing_period_start'), name='uniq_invoice_per_contract_period'),
        ),
    ]
