# Generated by Django 6.0.4 on 2026-09-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0025_remediationsuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='vendor_end_of_life',
            field=models.DateField(blank=True, help_text="Vendor's announced end-of-life / end-of-sale date for this model. Overrides the estimate derived from purchase date.", null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='vendor_end_of_support',
            field=models.DateField(blank=True, help_text='Last day the vendor will support it. After this, security fixes stop arriving.', null=True),
        ),
    ]
