# Generated by Django 6.0.4 on 2026-09-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0008_sync_importjob_field_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='csv_target_model',
            field=models.CharField(blank=True, choices=[('asset', 'Assets'), ('password', 'Passwords (Vault)'), ('contact', 'Contacts'), ('document', 'Documents'), ('shop_inventory', 'Shop Inventory'), ('vehicle_inventory', 'Vehicle / VAN Inventory')], help_text='What to import CSV rows as (CSV imports only)', max_length=20),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='source_file',
            field=models.FileField(blank=True, help_text='Upload file: MagicPlan JSON export, CSV, or .xlsx spreadsheet', null=True, upload_to='imports/files/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='source_type',
            field=models.CharField(choices=[('itglue', 'IT Glue'), ('hudu', 'Hudu'), ('magicplan', 'MagicPlan Floor Plans'), ('csv', 'CSV / Spreadsheet (.csv, .xlsx)')], max_length=20),
        ),
    ]
