# Generated by Django 6.0.1 on 2026-01-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_feature_toggles'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preset_background',
            field=models.CharField(blank=True, choices=[('abstract-1', 'Purple Gradient'), ('abstract-2', 'Blue Wave'), ('abstract-3', 'Orange Sunset'), ('abstract-4', 'Green Aurora'), ('abstract-5', 'Pink Nebula'), ('abstract-6', 'Cyan Fluid'), ('abstract-7', 'Red Geometric'), ('abstract-8', 'Teal Gradient'), ('abstract-9', 'Yellow Light'), ('abstract-10', 'Indigo Smoke'), ('abstract-11', 'Magenta Flow'), ('abstract-12', 'Navy Waves')], default='abstract-1', help_text='Select a preset abstract background', max_length=50),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('owner', 'Owner'), ('readonly', 'Read-Only')], default='readonly', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='auth_source',
            field=models.CharField(choices=[('azure_ad', 'Azure AD / Microsoft Entra ID'), ('ldap', 'LDAP/Active Directory'), ('local', 'Local')], default='local', help_text='Authentication source for this user', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='background_mode',
            field=models.CharField(choices=[('custom', 'Custom Upload'), ('none', 'No Background Image'), ('preset', 'Preset Abstract Backgrounds'), ('random', 'Random from Internet')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('de', 'German'), ('es', 'Spanish')], default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notification_frequency',
            field=models.CharField(choices=[('daily', 'Daily Digest'), ('hourly', 'Hourly Digest'), ('realtime', 'Real-time'), ('weekly', 'Weekly Digest')], default='realtime', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(choices=[('dark', 'Dark Mode'), ('default', 'Default Blue'), ('dracula', 'Dracula'), ('green', 'Forest Green'), ('gruvbox', 'Gruvbox'), ('monokai', 'Monokai'), ('nord', 'Nord (Arctic)'), ('ocean', 'Ocean Blue'), ('purple', 'Purple Haze'), ('solarized', 'Solarized Light'), ('sunset', 'Sunset Orange')], default='default', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='two_factor_method',
            field=models.CharField(blank=True, choices=[('totp', 'Authenticator App'), ('email', 'Email'), ('sms', 'SMS')], default='totp', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('org_user', 'Organization User (Client)'), ('staff', 'Staff User (MSP Tech)')], default='org_user', help_text='Staff users have global access across all organizations. Org users only see their assigned organizations.', max_length=20),
        ),
    ]
