# Generated by Django 6.0.1 on 2026-01-29 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_solid_color_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tooltips_enabled',
            field=models.BooleanField(default=True, help_text='Show helpful tooltips throughout the interface'),
        ),
    ]
