# Generated by Django 6.0.4 on 2026-09-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_add_ticket_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='background_mode',
            field=models.CharField(choices=[('custom', 'Custom Upload'), ('none', 'No Background Image'), ('preset', 'Preset Abstract Backgrounds'), ('random', 'Random from Internet'), ('solid_color', 'Solid Color')], default='preset', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preset_background',
            field=models.CharField(blank=True, choices=[('abstract-1', 'Purple Gradient'), ('abstract-2', 'Blue Gradient'), ('abstract-3', 'Orange Coral'), ('abstract-4', 'Teal Wave'), ('abstract-5', 'Pink Nebula'), ('abstract-6', 'Cyan Fluid'), ('abstract-7', 'Red Geometric'), ('abstract-8', 'Blue Teal'), ('abstract-9', 'Yellow Gold'), ('abstract-10', 'Indigo Dark'), ('abstract-11', 'Magenta Flow'), ('abstract-12', 'Navy Space')], default='abstract-12', help_text='Select a preset abstract background', max_length=50),
        ),
    ]
