# Generated by Django 6.0.4 on 2026-09-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_alter_userprofile_background_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roletemplate',
            name='network_discovery_generate',
            field=models.BooleanField(default=False, help_text='Generate remote network discovery scripts and tokens'),
        ),
    ]
