# Generated by Django 6.0.1 on 2026-01-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0010_alter_documentcategory_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, help_text='Uploaded file (PDF, DOCX, images, etc.)', null=True, upload_to='documents/files/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.BigIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='file_type',
            field=models.CharField(blank=True, help_text='MIME type of uploaded file', max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='content_type',
            field=models.CharField(choices=[('html', 'HTML (WYSIWYG)'), ('markdown', 'Markdown'), ('file', 'Uploaded File')], default='html', max_length=20),
        ),
    ]
