# Generated by Django 6.0.4 on 2026-09-03 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_alter_scheduledtask_task_type'),
        ('inventory', '0002_inventoryitem_last_replenished_at_and_more'),
        ('vehicles', '0008_vendor_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, help_text='Asset tag or internal identifier, e.g. TL-014.', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('condition', models.CharField(choices=[('good', 'Good'), ('needs_service', 'Needs service'), ('out_of_service', 'Out of service'), ('lost', 'Lost')], default='good', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to retire a tool without deleting its history.')),
                ('notes', models.TextField(blank=True)),
                ('assigned_vehicle', models.ForeignKey(blank=True, help_text='Van this tool normally rides in, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to='vehicles.servicevehicle')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to='inventory.inventorycategory')),
                ('home_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to='inventory.inventorylocation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='core.organization')),
            ],
            options={
                'db_table': 'inventory_tools',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['organization', 'is_active'], name='inventory_t_organiz_3fdc3b_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('code__gt', '')), fields=('organization', 'code'), name='uniq_tool_code_per_org')],
            },
        ),
    ]
