# Generated by Django 6.0.4 on 2026-08-01 22:13

"""Catch up the migration state with the ``SavedQuery.target_model`` choices
(v3.17.509).

``choices`` and ``help_text`` are Python-level attributes — ``sqlmigrate`` on
this migration emits ``-- (no-op)``. It exists only so ``makemigrations --check``
is clean and a fresh install's recorded state matches the model.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_savedquery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedquery',
            name='target_model',
            field=models.CharField(choices=[('psa.Ticket', 'PSA Tickets'), ('assets.Asset', 'Assets'), ('vault.Password', 'Vault Passwords'), ('psa.Invoice', 'Invoices'), ('psa.TicketTimeEntry', 'Time Entries')], help_text='Which app+model to query.', max_length=80),
        ),
    ]
