# Generated by Django 6.0.1 on 2026-02-04 17:27

from django.db import migrations, models


def remove_index_if_exists(apps, schema_editor):
    """
    Safely remove the lat/lon index if it exists.
    This prevents migration failures on fresh installs where the index was never created.
    """
    db_alias = schema_editor.connection.alias

    # Get the RMMDevice model
    RMMDevice = apps.get_model('integrations', 'RMMDevice')

    # Check if index exists by querying the database
    with schema_editor.connection.cursor() as cursor:
        # For PostgreSQL
        if schema_editor.connection.vendor == 'postgresql':
            cursor.execute(
                "SELECT 1 FROM pg_indexes WHERE indexname = %s",
                ['rmm_devices_lat_lon_idx']
            )
            if cursor.fetchone():
                cursor.execute("DROP INDEX IF EXISTS rmm_devices_lat_lon_idx")

        # For SQLite
        elif schema_editor.connection.vendor == 'sqlite':
            cursor.execute(
                "SELECT name FROM sqlite_master WHERE type='index' AND name='rmm_devices_lat_lon_idx'"
            )
            if cursor.fetchone():
                cursor.execute("DROP INDEX IF EXISTS rmm_devices_lat_lon_idx")

        # For MySQL
        elif schema_editor.connection.vendor == 'mysql':
            cursor.execute(
                "SELECT 1 FROM information_schema.statistics WHERE index_name = %s AND table_name = 'rmm_devices'",
                ['rmm_devices_lat_lon_idx']
            )
            if cursor.fetchone():
                cursor.execute("DROP INDEX rmm_devices_lat_lon_idx ON rmm_devices")


def reverse_remove_index(apps, schema_editor):
    """
    Reverse operation: recreate the index.
    """
    RMMDevice = apps.get_model('integrations', 'RMMDevice')

    with schema_editor.connection.cursor() as cursor:
        # For PostgreSQL
        if schema_editor.connection.vendor == 'postgresql':
            cursor.execute(
                "CREATE INDEX IF NOT EXISTS rmm_devices_lat_lon_idx ON rmm_devices (latitude, longitude)"
            )
        # For SQLite
        elif schema_editor.connection.vendor == 'sqlite':
            cursor.execute(
                "CREATE INDEX IF NOT EXISTS rmm_devices_lat_lon_idx ON rmm_devices (latitude, longitude)"
            )
        # For MySQL
        elif schema_editor.connection.vendor == 'mysql':
            cursor.execute(
                "CREATE INDEX rmm_devices_lat_lon_idx ON rmm_devices (latitude, longitude)"
            )


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_add_device_location_fields'),
    ]

    operations = [
        migrations.RunPython(
            remove_index_if_exists,
            reverse_code=reverse_remove_index,
        ),
        migrations.AddField(
            model_name='rmmdevice',
            name='site_id',
            field=models.CharField(blank=True, help_text='RMM site/client ID', max_length=255),
        ),
        migrations.AddField(
            model_name='rmmdevice',
            name='site_name',
            field=models.CharField(blank=True, help_text='RMM site/client name', max_length=255),
        ),
        migrations.AlterField(
            model_name='psaconnection',
            name='provider_type',
            field=models.CharField(choices=[('alga_psa', 'Alga PSA'), ('autotask', 'Autotask PSA'), ('connectwise_manage', 'ConnectWise Manage'), ('freshservice', 'Freshservice'), ('halo_psa', 'HaloPSA'), ('itflow', 'ITFlow'), ('kaseya_bms', 'Kaseya BMS'), ('rangermsp', 'RangerMSP (CommitCRM)'), ('syncro', 'Syncro'), ('zendesk', 'Zendesk')], max_length=50),
        ),
        migrations.AlterField(
            model_name='psaticket',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('low', 'Low'), ('medium', 'Medium'), ('urgent', 'Urgent')], default='medium', max_length=50),
        ),
        migrations.AlterField(
            model_name='psaticket',
            name='status',
            field=models.CharField(choices=[('closed', 'Closed'), ('in_progress', 'In Progress'), ('new', 'New'), ('resolved', 'Resolved'), ('waiting', 'Waiting')], default='new', max_length=50),
        ),
        migrations.AlterField(
            model_name='rmmconnection',
            name='provider_type',
            field=models.CharField(choices=[('atera', 'Atera'), ('connectwise_automate', 'ConnectWise Automate'), ('datto_rmm', 'Datto RMM'), ('ninjaone', 'NinjaOne'), ('tactical_rmm', 'Tactical RMM')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rmmdevice',
            name='device_type',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('mobile', 'Mobile Device'), ('network', 'Network Device'), ('server', 'Server'), ('unknown', 'Unknown'), ('virtual', 'Virtual Machine'), ('workstation', 'Workstation')], default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='rmmdevice',
            name='os_type',
            field=models.CharField(blank=True, choices=[('android', 'Android'), ('ios', 'iOS'), ('linux', 'Linux'), ('macos', 'macOS'), ('other', 'Other'), ('windows', 'Windows')], max_length=50),
        ),
    ]
