# Generated by Django 6.0.4 on 2026-09-03 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_systemsetting_background_color_and_more'),
        ('integrations', '0027_warrantyconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingCustomerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_customer_id', models.CharField(help_text='Customer Id in the accounting system.', max_length=120)),
                ('display_name', models.CharField(blank=True, help_text='Provider-side DisplayName, kept for reporting and matching.', max_length=255)),
                ('source', models.CharField(choices=[('push', 'Created here, pushed to the provider'), ('matched', 'Matched an existing provider customer by name'), ('pull', 'Imported from the provider')], default='push', max_length=20)),
                ('last_pushed_at', models.DateTimeField(blank=True, null=True)),
                ('last_pulled_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('client_org', models.ForeignKey(help_text='The client this provider customer represents.', on_delete=django.db.models.deletion.CASCADE, related_name='accounting_customer_mappings', to='core.organization')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_links', to='integrations.accountingconnection')),
                ('organization', models.ForeignKey(help_text='The tenant that owns the connection.', on_delete=django.db.models.deletion.CASCADE, related_name='accounting_customer_links', to='core.organization')),
            ],
            options={
                'db_table': 'accounting_customer_links',
                'ordering': ['display_name'],
                'indexes': [models.Index(fields=['organization', 'connection'], name='accounting__organiz_91fdd4_idx')],
                'constraints': [models.UniqueConstraint(fields=('connection', 'client_org'), name='uniq_accounting_link_per_client'), models.UniqueConstraint(fields=('connection', 'provider_customer_id'), name='uniq_accounting_link_per_customer')],
            },
        ),
    ]
