# Generated by Django 6.0.4 on 2026-09-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0029_migrate_customer_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingauditlog',
            name='action',
            field=models.CharField(choices=[('push_invoice', 'Push Invoice'), ('record_payment', 'Record Payment'), ('test_connection', 'Test Connection'), ('refresh_token', 'Refresh Token'), ('poll_balance', 'Poll Invoice Balance'), ('push_customer', 'Push Customer'), ('pull_customers', 'Pull Customers'), ('pull_payments', 'Pull Payments'), ('pull_invoices', 'Pull Invoice State')], max_length=40),
        ),
    ]
