# Generated by Django 6.0.2 on 2026-02-21 23:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinventoryitem',
            name='reorder_quantity',
            field=models.IntegerField(default=0, help_text='How many to order when restocking', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
