# Generated by Django 6.0.1 on 2026-01-11 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_add_rackmount_fields'),
        ('monitoring', '0004_change_asset_id_to_foreignkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='ambient_temp_f',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ambient temperature (°F)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='rack',
            name='building',
            field=models.CharField(blank=True, help_text='Building name/number', max_length=100),
        ),
        migrations.AddField(
            model_name='rack',
            name='closet_diagram',
            field=models.ImageField(blank=True, help_text='Network closet layout diagram or photo', null=True, upload_to='rack_diagrams/'),
        ),
        migrations.AddField(
            model_name='rack',
            name='floor',
            field=models.CharField(blank=True, help_text='Floor level', max_length=50),
        ),
        migrations.AddField(
            model_name='rack',
            name='patch_panel_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of patch panels'),
        ),
        migrations.AddField(
            model_name='rack',
            name='pdu_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of Power Distribution Units'),
        ),
        migrations.AddField(
            model_name='rack',
            name='rack_type',
            field=models.CharField(choices=[('full_rack', 'Full Rack (42U+)'), ('half_rack', 'Half Rack (20U-25U)'), ('data_closet', 'Data Closet'), ('network_closet', 'Network Closet'), ('wall_mount', 'Wall Mount Rack'), ('open_frame', 'Open Frame Rack'), ('cabinet', 'Server Cabinet')], default='full_rack', help_text='Type of rack or closet', max_length=50),
        ),
        migrations.AddField(
            model_name='rack',
            name='room',
            field=models.CharField(blank=True, help_text='Room number/name', max_length=50),
        ),
        migrations.AddField(
            model_name='rack',
            name='total_port_count',
            field=models.PositiveIntegerField(default=0, help_text='Total network ports'),
        ),
        migrations.CreateModel(
            name='RackResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('patch_panel', 'Patch Panel'), ('switch', 'Network Switch'), ('router', 'Router'), ('firewall', 'Firewall'), ('ups', 'UPS/Battery Backup'), ('pdu', 'Power Distribution Unit'), ('cable_mgmt', 'Cable Management'), ('shelf', 'Shelf/Tray'), ('kvm', 'KVM Switch'), ('monitor', 'Monitor/Display'), ('keystone', 'Keystone Jacks'), ('fiber_panel', 'Fiber Patch Panel'), ('other', 'Other Equipment')], max_length=50)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('port_count', models.PositiveIntegerField(blank=True, help_text='Number of ports (for switches/patch panels)', null=True)),
                ('port_speed', models.CharField(blank=True, help_text='e.g., 1Gbps, 10Gbps', max_length=50)),
                ('power_draw_watts', models.PositiveIntegerField(blank=True, null=True)),
                ('input_voltage', models.CharField(blank=True, help_text='e.g., 120V, 240V', max_length=50)),
                ('battery_runtime_minutes', models.PositiveIntegerField(blank=True, help_text='Runtime at full load', null=True)),
                ('capacity_va', models.PositiveIntegerField(blank=True, help_text='VA capacity for UPS', null=True)),
                ('rack_position', models.PositiveIntegerField(blank=True, help_text='U position if rack-mounted', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Management IP', null=True)),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('management_url', models.URLField(blank=True, max_length=500)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_expires', models.DateField(blank=True, null=True)),
                ('support_contract', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='rack_resources/')),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rack_resources', to='assets.asset')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='monitoring.rack')),
            ],
            options={
                'db_table': 'rack_resources',
                'ordering': ['rack', 'resource_type', 'name'],
                'indexes': [models.Index(fields=['rack', 'resource_type'], name='rack_resour_rack_id_b68ce8_idx'), models.Index(fields=['ip_address'], name='rack_resour_ip_addr_377917_idx')],
            },
        ),
    ]
