# Generated by Django 6.0.2 on 2026-02-21 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_add_vlan_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='RackConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection_type', models.CharField(choices=[('network', 'Network Cable'), ('fiber', 'Fiber Optic'), ('power', 'Power Cable'), ('console', 'Console Cable'), ('storage', 'Storage (SAN/NAS)')], max_length=50)),
                ('from_port', models.CharField(blank=True, help_text='Source port (e.g., eth0, port 24)', max_length=50)),
                ('to_port', models.CharField(blank=True, help_text='Destination port', max_length=50)),
                ('cable_color', models.CharField(default='#0d6efd', help_text='Cable color for visualization', max_length=7)),
                ('speed', models.CharField(blank=True, help_text='Connection speed (e.g., 1Gbps, 10Gbps)', max_length=50)),
                ('from_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_from', to='monitoring.rackdevice')),
                ('to_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_to', to='monitoring.rackdevice')),
            ],
            options={
                'db_table': 'rack_connections',
            },
        ),
    ]
