# Generated by Django 6.0.2 on 2026-02-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_add_port_configuration_to_rack_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='rackdevice',
            name='board_height',
            field=models.PositiveIntegerField(blank=True, help_text='Height on board (pixels)', null=True),
        ),
        migrations.AddField(
            model_name='rackdevice',
            name='board_position_x',
            field=models.PositiveIntegerField(blank=True, help_text='X position on board (pixels)', null=True),
        ),
        migrations.AddField(
            model_name='rackdevice',
            name='board_position_y',
            field=models.PositiveIntegerField(blank=True, help_text='Y position on board (pixels)', null=True),
        ),
        migrations.AddField(
            model_name='rackdevice',
            name='board_width',
            field=models.PositiveIntegerField(blank=True, help_text='Width on board (pixels)', null=True),
        ),
        migrations.AddField(
            model_name='rackresource',
            name='board_height',
            field=models.PositiveIntegerField(blank=True, help_text='Height on board (pixels)', null=True),
        ),
        migrations.AddField(
            model_name='rackresource',
            name='board_position_x',
            field=models.PositiveIntegerField(blank=True, help_text='X position on board (pixels)', null=True),
        ),
        migrations.AddField(
            model_name='rackresource',
            name='board_position_y',
            field=models.PositiveIntegerField(blank=True, help_text='Y position on board (pixels)', null=True),
        ),
        migrations.AddField(
            model_name='rackresource',
            name='board_width',
            field=models.PositiveIntegerField(blank=True, help_text='Width on board (pixels)', null=True),
        ),
    ]
