# Generated by Django 6.0.4 on 2026-09-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0012_monitorcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='expiration',
            name='notification_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='websitemonitor',
            name='domain_expiry_notified_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='websitemonitor',
            name='ssl_expiry_notified_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
