# Generated by Django 6.0.1 on 2026-02-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_add_property_diagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
